#:schema node_modules/wrangler/config-schema.json
name = "litebible"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[env.production]
name = "litebible"

[build]
command = "echo 'No build needed'"