// Initial Bible data for fast loading - Complete John chapters
export default [
  ["John", [
    // John 1
    [
      "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "He was with God in the beginning.",
      "Through Him all things were made, and without Him nothing was made that has been made.",
      "In Him was life, and that life was the light of men.",
      "The Light shines in the darkness, and the darkness has not overcome it.",
      "There came a man who was sent from God. His name was John.",
      "He came as a witness to testify about the Light, so that through him everyone might believe.",
      "He himself was not the Light, but he came to testify about the Light.",
      "The true Light who gives light to every man was coming into the world.",
      "He was in the world, and though the world was made through Him, the world did not recognize Him.",
      "He came to His own, and His own did not receive Him.",
      "But to all who did receive Him, to those who believed in His name, He gave the right to become children of God—",
      "children born not of blood, nor of the desire or will of man, but born of God.",
      "The Word became flesh and made His dwelling among us. We have seen His glory, the glory of the one and only Son from the Father, full of grace and truth.",
      "John testified concerning Him. He cried out, saying, “This is He of whom I said, ‘He who comes after me has surpassed me because He was before me.’”",
      "From His fullness we have all received grace upon grace.",
      "For the law was given through Moses; grace and truth came through Jesus Christ.",
      "No one has ever seen God, but the one and only Son, who is Himself God and is at the Father’s side, has made Him known.",
      "And this was John’s testimony when the Jews of Jerusalem sent priests and Levites to ask him, “Who are you?”",
      "He did not refuse to confess, but openly declared, “I am not the Christ.”",
      "“Then who are you?” they inquired. “Are you Elijah?”  He said, “I am not.”  “Are you the Prophet?”  He answered, “No.”",
      "So they said to him, “Who are you? We need an answer for those who sent us. What do you say about yourself?”",
      "John replied in the words of Isaiah the prophet:  “I am a voice of one calling in the wilderness, ‘Make straight the way for the Lord.’”",
      "Then the Pharisees who had been sent",
      "asked him, “Why then do you baptize, if you are not the Christ, nor Elijah, nor the Prophet?”",
      "“I baptize with water,” John replied, “but among you stands One you do not know.",
      "He is the One who comes after me, the straps of whose sandals I am not worthy to untie.”",
      "All this happened at Bethany beyond the Jordan, where John was baptizing.",
      "The next day John saw Jesus coming toward him and said, “Look, the Lamb of God, who takes away the sin of the world!",
      "This is He of whom I said, ‘A man who comes after me has surpassed me because He was before me.’",
      "I myself did not know Him, but the reason I came baptizing with water was that He might be revealed to Israel.”",
      "Then John testified, “I saw the Spirit descending from heaven like a dove and resting on Him.",
      "I myself did not know Him, but the One who sent me to baptize with water told me, ‘The man on whom you see the Spirit descend and rest is He who will baptize with the Holy Spirit.’",
      "I have seen and testified that this is the Son of God.”",
      "The next day John was there again with two of his disciples.",
      "When he saw Jesus walking by, he said, “Look, the Lamb of God!”",
      "And when the two disciples heard him say this, they followed Jesus.",
      "Jesus turned and saw them following. “What do you want?” He asked.  They said to Him, “Rabbi” (which means Teacher), “where are You staying?”",
      "“Come and see,” He replied. So they went and saw where He was staying, and spent that day with Him. It was about the tenth hour.",
      "Andrew, Simon Peter’s brother, was one of the two who heard John’s testimony and followed Jesus.",
      "He first found his brother Simon and told him, “We have found the Messiah” (which is translated as Christ).",
      "Andrew brought him to Jesus, who looked at him and said, “You are Simon son of John. You will be called Cephas” (which is translated as Peter).",
      "The next day Jesus decided to set out for Galilee. Finding Philip, He told him, “Follow Me.”",
      "Now Philip was from Bethsaida, the same town as Andrew and Peter.",
      "Philip found Nathanael and told him, “We have found the One Moses wrote about in the Law, the One the prophets foretold—Jesus of Nazareth, the son of Joseph.”",
      "“Can anything good come from Nazareth?” Nathanael asked.  “Come and see,” said Philip.",
      "When Jesus saw Nathanael approaching, He said of him, “Here is a true Israelite, in whom there is no deceit.”",
      "“How do You know me?” Nathanael asked.  Jesus replied, “Before Philip called you, I saw you under the fig tree.”",
      "“Rabbi,” Nathanael answered, “You are the Son of God! You are the King of Israel!”",
      "Jesus said to him, “Do you believe just because I told you I saw you under the fig tree? You will see greater things than these.”",
      "Then He declared, “Truly, truly, I tell you, you will all see heaven open and the angels of God ascending and descending on the Son of Man.”"
    ],
    // John 2
    [
      "On the third day a wedding took place at Cana in Galilee. Jesus’ mother was there,",
      "and Jesus and His disciples had also been invited to the wedding.",
      "When the wine ran out, Jesus’ mother said to Him, “They have no more wine.”",
      "“Woman, why does this concern us?” Jesus replied. “My hour has not yet come.”",
      "His mother said to the servants, “Do whatever He tells you.”",
      "Now six stone water jars had been set there for the Jewish rites of purification. Each could hold from twenty to thirty gallons.",
      "Jesus told the servants, “Fill the jars with water.”  So they filled them to the brim.",
      "“Now draw some out,” He said, “and take it to the master of the banquet.”  They did so,",
      "and the master of the banquet tasted the water that had been turned into wine. He did not know where it was from, but the servants who had drawn the water knew. Then he called the bridegroom aside",
      "and said, “Everyone serves the fine wine first, and then the cheap wine after the guests are drunk. But you have saved the fine wine until now!”",
      "Jesus performed this, the first of His signs, at Cana in Galilee. He thus revealed His glory, and His disciples believed in Him.",
      "After this, He went down to Capernaum with His mother and brothers and His disciples, and they stayed there a few days.",
      "When the Jewish Passover was near, Jesus went up to Jerusalem.",
      "In the temple courts He found men selling cattle, sheep, and doves, and money changers seated at their tables.",
      "So He made a whip out of cords and drove all from the temple courts, both sheep and cattle. He poured out the coins of the money changers and overturned their tables.",
      "To those selling doves He said, “Get these out of here! How dare you turn My Father’s house into a marketplace!”",
      "His disciples remembered that it is written: “Zeal for Your house will consume Me.”",
      "On account of this, the Jews demanded, “What sign can You show us to prove Your authority to do these things?”",
      "Jesus answered, “Destroy this temple, and in three days I will raise it up again.”",
      "“This temple took forty-six years to build,” the Jews replied, “and You are going to raise it up in three days?”",
      "But Jesus was speaking about the temple of His body.",
      "After He was raised from the dead, His disciples remembered that He had said this. Then they believed the Scripture and the word that Jesus had spoken.",
      "While He was in Jerusalem at the Passover Feast, many people saw the signs He was doing and believed in His name.",
      "But Jesus did not entrust Himself to them, for He knew them all.",
      "He did not need any testimony about man, for He knew what was in a man."
    ],
    // John 3
    [
      "Now there was a man of the Pharisees named Nicodemus, a leader of the Jews.",
      "He came to Jesus at night and said, “Rabbi, we know that You are a teacher who has come from God. For no one could perform the signs You are doing if God were not with him.”",
      "Jesus replied, “Truly, truly, I tell you, no one can see the kingdom of God unless he is born again.”",
      "“How can a man be born when he is old?” Nicodemus asked. “Can he enter his mother’s womb a second time to be born?”",
      "Jesus answered, “Truly, truly, I tell you, no one can enter the kingdom of God unless he is born of water and the Spirit.",
      "Flesh is born of flesh, but spirit is born of the Spirit.",
      "Do not be amazed that I said, ‘You must be born again.’",
      "The wind blows where it wishes. You hear its sound, but you do not know where it comes from or where it is going. So it is with everyone born of the Spirit.”",
      "“How can this be?” Nicodemus asked.",
      "“You are Israel’s teacher,” said Jesus, “and you do not understand these things?",
      "Truly, truly, I tell you, we speak of what we know, and we testify to what we have seen, and yet you people do not accept our testimony.",
      "If I have told you about earthly things and you do not believe, how will you believe if I tell you about heavenly things?",
      "No one has ascended into heaven except the One who descended from heaven—the Son of Man.",
      "Just as Moses lifted up the snake in the wilderness, so the Son of Man must be lifted up,",
      "that everyone who believes in Him may have eternal life.",
      "For God so loved the world that He gave His one and only Son, that everyone who believes in Him shall not perish but have eternal life.",
      "For God did not send His Son into the world to condemn the world, but to save the world through Him.",
      "Whoever believes in Him is not condemned, but whoever does not believe has already been condemned, because he has not believed in the name of God’s one and only Son.",
      "And this is the verdict: The Light has come into the world, but men loved the darkness rather than the Light because their deeds were evil.",
      "Everyone who does evil hates the Light, and does not come into the Light for fear that his deeds will be exposed.",
      "But whoever practices the truth comes into the Light, so that it may be seen clearly that what he has done has been accomplished in God.”",
      "After this, Jesus and His disciples went into the Judean countryside, where He spent some time with them and baptized.",
      "Now John was also baptizing at Aenon near Salim, because the water was plentiful there, and people kept coming to be baptized.",
      "(For John had not yet been thrown into prison.)",
      "Then a dispute arose between John’s disciples and a certain Jew over the issue of ceremonial washing.",
      "So John’s disciples came to him and said, “Look, Rabbi, the One who was with you beyond the Jordan, the One you testified about—He is baptizing, and everyone is going to Him.”",
      "John replied, “A man can receive only what is given him from heaven.",
      "You yourselves can testify that I said, ‘I am not the Christ, but am sent ahead of Him.’",
      "The bride belongs to the bridegroom. The friend of the bridegroom stands and listens for him, and is overjoyed to hear the bridegroom’s voice. That joy is mine, and it is now complete.",
      "He must increase; I must decrease.",
      "The One who comes from above is above all. The one who is from the earth belongs to the earth and speaks as one from the earth. The One who comes from heaven is above all.",
      "He testifies to what He has seen and heard, yet no one accepts His testimony.",
      "Whoever accepts His testimony has certified that God is truthful.",
      "For the One whom God has sent speaks the words of God, for God gives the Spirit without limit.",
      "The Father loves the Son and has placed all things in His hands.",
      "Whoever believes in the Son has eternal life. Whoever rejects the Son will not see life. Instead, the wrath of God remains on him.”"
    ]
  ]]
];